[package]
name = "efi_ffi"
version = "0.1.0"
authors = ["Gurinder Singh <gurinder.singh@1e.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
